os: Visual Studio 2017
version: '{branch}-{build}'
clone_depth: 5
install:
- git clone -q --branch 2019.1 https://github.com/uglide/RedisDesktopManager.git C:\projects\RedisDesktopManager
- set QTDIR=C:\Qt\5.9\msvc2017_64
- set APPPATH=C:\projects\RedisDesktopManager
- set PATH=%QTDIR%\bin;%PATH%
- cd %APPPATH%
- git submodule update --init --recursive
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
- powershell -command "iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))"
- qmake -v

build_script:
- set SRCDIR=%APPPATH%
- dir %SRCDIR%
- cd %SRCDIR%
- python ./build/utils/set_version.py %APPVEYOR_BUILD_VERSION% > ./src/version.h
- python ./build/utils/set_version.py %APPVEYOR_BUILD_VERSION% > ./3rdparty/crashreporter/src/version.h
- cd ./3rdparty/crashreporter
- cd %SRCDIR%\3rdparty\crashreporter
- qmake CONFIG+=release DESTDIR=%SRCDIR%\bin\windows\release
- powershell -Command "(Get-Content Makefile.Release).replace('DEFINES       =', 'DEFINES       = -DAPP_NAME=\\\"RedisDesktopManager\\\" -DAPP_VERSION=\\\""%APPVEYOR_BUILD_VERSION%"\\\" -DCRASH_SERVER_URL=\\\"https://oops.redisdesktop.com/crash-report\\\"') " > Makefile.Release2
- nmake -f Makefile.Release2
- cd %SRCDIR%/3rdparty
- nuget install zlib-msvc14-x64 -Version 1.2.11.7795
- cd %SRCDIR%/src
- lrelease rdm.pro
- qmake CONFIG+=release
- nmake /S /NOLOGO release
- cd %SRCDIR%
- copy /y .\bin\windows\release\rdm.exe .\build\windows\installer\resources\rdm.exe
- copy /y .\bin\windows\release\crashreporter.exe .\build\windows\installer\resources\crashreporter.exe
- copy /y .\bin\windows\release\rdm.pdb .\build\windows\installer\resources\rdm.pdb
- copy /y .\3rdparty\qredisclient\botan.dll .\build\windows\installer\resources\botan.dll
- "%SRCDIR%/3rdparty/gbreakpad/src/tools/windows/binaries/dump_syms .\\bin\\windows\\release\\rdm.pdb  > .\\build\\windows\\installer\\resources\\rdm.sym"
- cd %APPPATH%\build\windows\installer\resources\
- windeployqt --no-angle --no-opengl-sw --no-compiler-runtime --no-translations --release --force --qmldir %SRCDIR%\src\qml rdm.exe
- rmdir /S /Q %APPPATH%\platforminputcontexts
- rmdir /S /Q %APPPATH%\qmltooling
- rmdir /S /Q %APPPATH%\QtGraphicalEffects
- del /Q  %APPPATH%\imageformats\qtiff.dll
- del /Q  %APPPATH%\imageformats\qwebp.dll
- C:\Python37\python.exe -m pip install -t . -r %SRCDIR%/src/py/requirements.txt
- cd %SRCDIR%
- 7z.exe a redis-desktop-manager-%APPVEYOR_BUILD_VERSION%.zip ./build/windows/installer/resources/*
test_script:
- echo 'Windows build is used only for installer compilation. Skip tests.'
artifacts:
  - path: "%SRCDIR%\\redis-desktop-manager-%APPVEYOR_BUILD_VERSION%.zip"
