os: Visual Studio 2017
version: 0.9.2.{build}
clone_depth: 5
install:
- git clone -q --depth=5 --branch=2019 https://github.com/uglide/RedisDesktopManager.git C:\projects\redisdesktopmanager
- set SRCDIR=C:\projects\RedisDesktopManager
- set QTDIR=C:\Qt\5.9\msvc2017_64
- set PATH=%QTDIR%\bin;%PATH%
- cd %SRCDIR%
- git checkout -qf 7a7118d22504c53d2fcd4c2e75d2e1fbdac28084
- git submodule update --init --recursive
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
- powershell -command "iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))"
- qmake -v
- set

build_script:
- cd %SRCDIR%
- python ./build/utils/set_version.py %APPVEYOR_BUILD_VERSION% > ./src/version.h
- python ./build/utils/set_version.py %APPVEYOR_BUILD_VERSION% > ./3rdparty/crashreporter/src/version.h
- cd ./3rdparty/crashreporter
- qmake CONFIG+=release DESTDIR=%SRCDIR%/bin/windows/release
- powershell -Command "(Get-Content Makefile.Release).replace('DEFINES       =', 'DEFINES       = -DAPP_NAME=\\\"RedisDesktopManager\\\" -DAPP_VERSION=\\\""%APPVEYOR_BUILD_VERSION%"\\\" -DCRASH_SERVER_URL=\\\"https://oops.redisdesktop.com/crash-report\\\"') " > Makefile.Release2
- nmake -f Makefile.Release2
- cd %SRCDIR%/3rdparty
- nuget install zlib-msvc14-x64 -Version 1.2.11.7795
- git clone https://github.com/randombit/botan.git
- cd botan
- python configure.py
- cd ../qredisclient/3rdparty/hiredis
- git apply ../hiredis-win.patch
- cd %SRCDIR%/src
- lrelease rdm.pro
- qmake CONFIG+=release
- nmake /S /NOLOGO release
- cd %SRCDIR%
- copy /y .\bin\windows\release\rdm.exe .\build\windows\installer\resources\rdm.exe
- copy /y .\bin\windows\release\crashreporter.exe .\build\windows\installer\resources\crashreporter.exe
- copy /y .\bin\windows\release\rdm.pdb .\build\windows\installer\resources\rdm.pdb
- .\3rdparty\gbreakpad\src\tools\windows\binaries\dump_syms .\bin\windows\release\rdm.pdb > .\build\windows\installer\resources\rdm.sym
- cd build/windows/installer/resources/
- windeployqt --no-angle --no-opengl-sw --no-compiler-runtime --no-translations --release --force --qmldir %SRCDIR%/src/qml rdm.exe
- rmdir /S /Q .\platforminputcontexts
- rmdir /S /Q .\qmltooling
- rmdir /S /Q .\QtGraphicalEffects
- del /Q  .\imageformats\qtiff.dll
- del /Q  .\imageformats\qwebp.dll
- C:\Python37\python.exe -m pip install -t . -r %SRCDIR%/src/py/requirements.txt
- cd %SRCDIR%
- 7z.exe a redis-desktop-manager-%APPVEYOR_BUILD_VERSION%.zip ./build/windows/installer/resources/*
artifacts:
- path: '**\*.zip'
